# Generated by Django 5.0.7 on 2024-08-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='comments',
        ),
    ]
